def liste_des_diviseurs(nb):
    tab_diviseur = ..........
    for i in range(1,nb):
        if .............
            tab_diviseur..........
    return .........

def est_parfait(nb):
    .........