def dicoAtome(molecule):
    ...

def factoriser(dicoMolecule):
    molecule = ...
    for ...:
        if ... :
            molecule += ...
        elif ...:
            molecule += ...
    return molecule