def echange(tab, i1, i2):
   ...


def inverse_tableau(tab):
    i = ...
    while ...:
        echange(..., ..., ...)
        i = ...


def inverse_chaine(chaine):
    ...
    inverse_tableau(...)
    return ...