#Exercice 1
def somme_chiffres(tableau_chiffres):
    ...


# Exercice 2
def mise_en_tableau(nombre):
    tableau_chiffres = [0] * ...
    while nombre != ...:
        unite = nombre % ...
        tableau_chiffres[...] = tableau_chiffres[...] + 1
        nombre = ... // ...
    return ...


